server:
    port: 9000
    contextPath:

spring:
    profiles:
        active: asb

    thymeleaf:
        cache: false

    jade4j:
        caching: false

    dataSource:
      driverClassName: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
      username: smas
      password: smas

    hibernate:
      dialect: org.hibernate.dialect.Oracle10gDialect
      hbm2ddl.auto: update
      show_sql: false

    redis:
      host: localhost
      port: 6379
      default_expire_time: 86400
logging:
    config: classpath:logback-spring.xml
    path: ../logs
    level: debug
cdcp :
    nodes :
      - ronnie
      - chloe



